version: "3"
services:
  node:
    image: "node:lts-alpine"
    user: "root"
    working_dir: /home/node/app
    volumes:
      - ./server/:/home/node/app
    command: ash -c "npm i && node index.js"
  nginx:
    image: jonasal/nginx-certbot:3.2.2-nginx1.23.2-alpine
    restart: unless-stopped
    env_file:
      - ./docker/nginx-certbot.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/conf.d/default.conf

volumes:
  nginx_secrets:
